### ISSUE TITLE
[BUG] Package installations fails on CentOS and Rocky Linux 8

### ISSUE THREAD

**Issue by emansom** [saltstack-formulas/wireguard-formula#3]
### Formula commit hash / release tag
b88246c2681b084232f25c04b45cbc5b6a9a1b01 / master

### Versions reports (master & minion)
```console
[root@REDACTED ~]# salt -V
Salt Version:
          Salt: 3004.1

Dependency Versions:
          cffi: 1.11.5
      cherrypy: unknown
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: 0.26.8
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.14
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: 0.26.4
        Python: 3.6.8 (default, Apr 12 2022, 06:55:39)
  python-gnupg: Not Installed
        PyYAML: 3.12
         PyZMQ: 19.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: rocky 8.6 Green Obsidian
        locale: UTF-8
       machine: x86_64
       release: 4.18.0-372.9.1.el8.x86_64
        system: Linux
       version: Rocky Linux 8.6 Green Obsidian
```

### Pillar / config used
`/srv/pillar/wireguard.sls`
```yaml
wireguard:
  interfaces:
    vpn0:
      Interface:
        Address: REDACTED
        SaveConfig: true
        ListenPort: REDACTED
        PrivateKey: REDACTED
      Peers:
        REDACTED:
          PublicKey: REDACTED
          AllowedIPs: REDACTED
          Endpoint: REDACTED
        REDACTED:
          PublicKey: REDACTED
          AllowedIPs: REDACTED
          Endpoint: REDACTED
```
---

### Describe the bug
When applying this state, it defaults to installing package `wireguard-redhat`, which is not available in CentOS nor Rocky Linux 8.

### Steps to reproduce the bug
Running the `wireguard` state on a CentOS Stream or Rocky Linux 8 machine.

### Expected behaviour
It defaulting to installation of the [`kmod-wireguard`](https://elrepo.org/tiki/kmod-wireguard) package from [ELRepo](https://elrepo.org/tiki/About) and the package [`wireguard-tools`](https://rpmfind.net/linux/RPM/epel/8/x86_64/Packages/w/wireguard-tools-1.0.20210914-1.el8.x86_64.html) from [EPEL](https://docs.fedoraproject.org/en-US/epel/), as [outlined in the official documentation](https://www.wireguard.com/install/#centos-8-module-plus-module-kmod-module-dkms-tools).

### Attempts to fix the bug

Will open up a PR shortly.
